[webserver]
# Remplacez par l'IP publique de la VM créée par OpenTofu
# (visible via `tofu output` dans votre projet de VM)
infomaniak_vm ansible_host=188.213.130.90 ansible_user=ubuntu ansible_ssh_private_key_file=/media/sergio/01DB9177DBBFFDD0/Cloud_ex/Infomaniak/SSH-sergio-ais-cloud.pem

[webserver:vars]
ansible_python_interpreter=/usr/bin/python3
