[webserver]
infomaniak_vm ansible_host=195.15.207.125 ansible_user=ubuntu ansible_ssh_private_key_file=/media/sergio/01DB9177DBBFFDD0/Cloud_ex/Infomaniak/SSH-sergio-ais-cloud.pem
[mail]
infomaniak_email ansible_host=195.15.207.241 ansible_user=ubuntu ansible_ssh_private_key_file=/media/sergio/01DB9177DBBFFDD0/Cloud_ex/Infomaniak/SSH-sergio-ais-cloud.pem

# For AWS
#[webserver]
#infomaniak_vm ansible_host=51.44.254.83 ansible_user=ubuntu ansible_ssh_private_key_file=/media/sergio/01DB9177DBBFFDD0/Cloud_ex/Infomaniak/ForAWS/Key-AWS.pem

[webserver:vars]
ansible_python_interpreter=/usr/bin/python3
