---
- name: Ensure roundcube directory exists on remote
  file:
    path: /opt/roundcube
    state: directory
    owner: ubuntu
    mode: "0755"

- name: Ensure roundcube/apache directory exists on remote
  file:
    path: /opt/roundcube/apache
    state: directory
    owner: ubuntu
    mode: "0755"


- name: Ensure roundcube/apache directory exists on remote
  file:
    path: /opt/roundcube/ssl
    state: directory
    owner: ubuntu
    mode: "0755"
    
- name: Generate private key for Roundcube
  community.crypto.openssl_privatekey:
    path: /opt/roundcube/ssl/mail.key
    size: 2048

- name: Generate CSR for Roundcube
  community.crypto.openssl_csr:
    path: /opt/roundcube/ssl/mail.csr
    privatekey_path: /opt/roundcube/ssl/mail.key
    common_name: mail.alpesnet.local

- name: Generate self-signed certificate for Roundcube
  community.crypto.x509_certificate:
    path: /opt/roundcube/ssl/mail.crt
    privatekey_path: /opt/roundcube/ssl/mail.key
    csr_path: /opt/roundcube/ssl/mail.csr
    provider: selfsigned
    selfsigned_create_subject_key_identifier: create_if_not_provided
    
    

- name: Copy Roundcube compose + config files
  copy:
    src: "{{ item }}"
    dest: "/opt/roundcube/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - config.inc.php

- name: Copy apache/ files
  copy:
    src: "apache/{{ item }}"
    dest: "/opt/roundcube/apache/{{ item }}"
    mode: "0644"
  loop:
    - Dockerfile
    - roundcube-ssl.conf

- name: Build and start Roundcube container
  community.docker.docker_compose_v2:
    project_src: /opt/roundcube
    state: present
    build: always
