---
- name: Mettre à jour le cache APT
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install docker dependencies
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: present

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Télécharger l'image nginx
  community.docker.docker_image:
    name: nginx
    source: pull

- name: Créer le conteneur nginx
  community.docker.docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    ports:
      - "81:80"
