---
#- name: Configurer nginx sur la VM Infomaniak
#  hosts: webserver
#  become: true

#  roles:
#    - nginx
    
- name: Installer Docker et lancer un conteneur
  hosts: webserver
  become: true

  roles:
    - FilesTree
    - docker
    - Borg
    - docker-nginx
    - nginx
    - docker-LDAP
    - docker-LAM
