protocols = imap
listen = *

mail_location = maildir:/var/mail/vhosts/alpesnet.local/%n

first_valid_uid = 5000
last_valid_uid = 5000

disable_plaintext_auth = no
auth_mechanisms = plain login

# Pour utiliser le mot de passe
#passdb {
#  driver = passwd-file
#  args = /etc/dovecot/passwd
#}

# Pour utiliser par ldap
passdb {
  driver = ldap
  args = /etc/dovecot/dovecot-ldap.conf.ext
}

userdb {
  driver = static
  args = uid=5000 gid=5000 home=/var/mail/vhosts/alpesnet.local/%n
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
    #user = 100
    #group = 102
    user = dovecot
    group = dovecot
  }
}

namespace inbox {
  inbox = yes
}
